name: pusher_beams
description: Official Flutter Plugin for Pusher Beams, receive notifications easily on your Flutter application with Pusher Beams.
version: 1.1.2
# repository: https://github.com/pusher/push-notifications-flutter
# issue_tracker: https://github.com/pusher/push-notifications-flutter/issues
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  pusher_beams_platform_interface: 
    path: ../pusher_beams_platform_interface
  pusher_beams_web: 
    path: ../pusher_beams_web
  pusher_beams_android: 
    path: ../pusher_beams_android
  pusher_beams_ios: 
    path: ../pusher_beams_ios 
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.0.16

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        default_package: pusher_beams_android
      ios:
        default_package: pusher_beams_ios
      web:
        default_package: pusher_beams_web